
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AppFooter': typeof import("../../components/AppFooter.vue").default
  'AppHeader': typeof import("../../components/AppHeader.vue").default
  'VoltAccordion': typeof import("../../components/volt/Accordion.vue").default
  'VoltAccordionContent': typeof import("../../components/volt/AccordionContent.vue").default
  'VoltAccordionHeader': typeof import("../../components/volt/AccordionHeader.vue").default
  'VoltAccordionPanel': typeof import("../../components/volt/AccordionPanel.vue").default
  'VoltAutoComplete': typeof import("../../components/volt/AutoComplete.vue").default
  'VoltAvatar': typeof import("../../components/volt/Avatar.vue").default
  'VoltAvatarGroup': typeof import("../../components/volt/AvatarGroup.vue").default
  'VoltBadge': typeof import("../../components/volt/Badge.vue").default
  'VoltBreadcrumb': typeof import("../../components/volt/Breadcrumb.vue").default
  'VoltButton': typeof import("../../components/volt/Button.vue").default
  'VoltButtonGroup': typeof import("../../components/volt/ButtonGroup.vue").default
  'VoltCard': typeof import("../../components/volt/Card.vue").default
  'VoltCheckbox': typeof import("../../components/volt/Checkbox.vue").default
  'VoltChip': typeof import("../../components/volt/Chip.vue").default
  'VoltConfirmDialog': typeof import("../../components/volt/ConfirmDialog.vue").default
  'VoltContrastButton': typeof import("../../components/volt/ContrastButton.vue").default
  'VoltDangerButton': typeof import("../../components/volt/DangerButton.vue").default
  'VoltDataTable': typeof import("../../components/volt/DataTable.vue").default
  'VoltDataView': typeof import("../../components/volt/DataView.vue").default
  'VoltDatePicker': typeof import("../../components/volt/DatePicker.vue").default
  'VoltDialog': typeof import("../../components/volt/Dialog.vue").default
  'VoltDivider': typeof import("../../components/volt/Divider.vue").default
  'VoltDrawer': typeof import("../../components/volt/Drawer.vue").default
  'VoltFieldset': typeof import("../../components/volt/Fieldset.vue").default
  'VoltFluid': typeof import("../../components/volt/Fluid.vue").default
  'VoltInplace': typeof import("../../components/volt/Inplace.vue").default
  'VoltInputMask': typeof import("../../components/volt/InputMask.vue").default
  'VoltInputNumber': typeof import("../../components/volt/InputNumber.vue").default
  'VoltInputOtp': typeof import("../../components/volt/InputOtp.vue").default
  'VoltInputText': typeof import("../../components/volt/InputText.vue").default
  'VoltListbox': typeof import("../../components/volt/Listbox.vue").default
  'VoltMenu': typeof import("../../components/volt/Menu.vue").default
  'VoltMessage': typeof import("../../components/volt/Message.vue").default
  'VoltMeterGroup': typeof import("../../components/volt/MeterGroup.vue").default
  'VoltMultiSelect': typeof import("../../components/volt/MultiSelect.vue").default
  'VoltOverlayBadge': typeof import("../../components/volt/OverlayBadge.vue").default
  'VoltPaginator': typeof import("../../components/volt/Paginator.vue").default
  'VoltPanel': typeof import("../../components/volt/Panel.vue").default
  'VoltPassword': typeof import("../../components/volt/Password.vue").default
  'VoltPopover': typeof import("../../components/volt/Popover.vue").default
  'VoltProgressBar': typeof import("../../components/volt/ProgressBar.vue").default
  'VoltProgressSpinner': typeof import("../../components/volt/ProgressSpinner.vue").default
  'VoltRadioButton': typeof import("../../components/volt/RadioButton.vue").default
  'VoltRating': typeof import("../../components/volt/Rating.vue").default
  'VoltSecondaryButton': typeof import("../../components/volt/SecondaryButton.vue").default
  'VoltSelect': typeof import("../../components/volt/Select.vue").default
  'VoltSelectButton': typeof import("../../components/volt/SelectButton.vue").default
  'VoltSkeleton': typeof import("../../components/volt/Skeleton.vue").default
  'VoltSlider': typeof import("../../components/volt/Slider.vue").default
  'VoltSplitter': typeof import("../../components/volt/Splitter.vue").default
  'VoltStep': typeof import("../../components/volt/Step.vue").default
  'VoltStepItem': typeof import("../../components/volt/StepItem.vue").default
  'VoltStepList': typeof import("../../components/volt/StepList.vue").default
  'VoltStepPanel': typeof import("../../components/volt/StepPanel.vue").default
  'VoltStepPanels': typeof import("../../components/volt/StepPanels.vue").default
  'VoltStepper': typeof import("../../components/volt/Stepper.vue").default
  'VoltTab': typeof import("../../components/volt/Tab.vue").default
  'VoltTabList': typeof import("../../components/volt/TabList.vue").default
  'VoltTabPanel': typeof import("../../components/volt/TabPanel.vue").default
  'VoltTabPanels': typeof import("../../components/volt/TabPanels.vue").default
  'VoltTabs': typeof import("../../components/volt/Tabs.vue").default
  'VoltTag': typeof import("../../components/volt/Tag.vue").default
  'VoltTextarea': typeof import("../../components/volt/Textarea.vue").default
  'VoltTimeline': typeof import("../../components/volt/Timeline.vue").default
  'VoltToast': typeof import("../../components/volt/Toast.vue").default
  'VoltToggleButton': typeof import("../../components/volt/ToggleButton.vue").default
  'VoltToggleSwitch': typeof import("../../components/volt/ToggleSwitch.vue").default
  'VoltToolbar': typeof import("../../components/volt/Toolbar.vue").default
  'VoltTree': typeof import("../../components/volt/Tree.vue").default
  'VoltUtils': typeof import("../../components/volt/utils").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default
  'AutoComplete': typeof import("primevue/autocomplete").default
  'Calendar': typeof import("primevue/calendar").default
  'CascadeSelect': typeof import("primevue/cascadeselect").default
  'Checkbox': typeof import("primevue/checkbox").default
  'CheckboxGroup': typeof import("primevue/checkboxgroup").default
  'Chips': typeof import("primevue/chips").default
  'ColorPicker': typeof import("primevue/colorpicker").default
  'DatePicker': typeof import("primevue/datepicker").default
  'Dropdown': typeof import("primevue/dropdown").default
  'FloatLabel': typeof import("primevue/floatlabel").default
  'Fluid': typeof import("primevue/fluid").default
  'IconField': typeof import("primevue/iconfield").default
  'IftaLabel': typeof import("primevue/iftalabel").default
  'InputChips': typeof import("primevue/inputchips").default
  'InputGroup': typeof import("primevue/inputgroup").default
  'InputGroupAddon': typeof import("primevue/inputgroupaddon").default
  'InputIcon': typeof import("primevue/inputicon").default
  'InputMask': typeof import("primevue/inputmask").default
  'InputNumber': typeof import("primevue/inputnumber").default
  'InputOtp': typeof import("primevue/inputotp").default
  'InputSwitch': typeof import("primevue/inputswitch").default
  'InputText': typeof import("primevue/inputtext").default
  'Knob': typeof import("primevue/knob").default
  'Listbox': typeof import("primevue/listbox").default
  'MultiSelect': typeof import("primevue/multiselect").default
  'Password': typeof import("primevue/password").default
  'RadioButton': typeof import("primevue/radiobutton").default
  'RadioButtonGroup': typeof import("primevue/radiobuttongroup").default
  'Rating': typeof import("primevue/rating").default
  'Select': typeof import("primevue/select").default
  'SelectButton': typeof import("primevue/selectbutton").default
  'Slider': typeof import("primevue/slider").default
  'Textarea': typeof import("primevue/textarea").default
  'ToggleButton': typeof import("primevue/togglebutton").default
  'ToggleSwitch': typeof import("primevue/toggleswitch").default
  'TreeSelect': typeof import("primevue/treeselect").default
  'Button': typeof import("primevue/button").default
  'ButtonGroup': typeof import("primevue/buttongroup").default
  'SpeedDial': typeof import("primevue/speeddial").default
  'SplitButton': typeof import("primevue/splitbutton").default
  'Column': typeof import("primevue/column").default
  'Row': typeof import("primevue/row").default
  'ColumnGroup': typeof import("primevue/columngroup").default
  'DataTable': typeof import("primevue/datatable").default
  'DataView': typeof import("primevue/dataview").default
  'OrderList': typeof import("primevue/orderlist").default
  'OrganizationChart': typeof import("primevue/organizationchart").default
  'Paginator': typeof import("primevue/paginator").default
  'PickList': typeof import("primevue/picklist").default
  'Tree': typeof import("primevue/tree").default
  'TreeTable': typeof import("primevue/treetable").default
  'Timeline': typeof import("primevue/timeline").default
  'VirtualScroller': typeof import("primevue/virtualscroller").default
  'Accordion': typeof import("primevue/accordion").default
  'AccordionPanel': typeof import("primevue/accordionpanel").default
  'AccordionHeader': typeof import("primevue/accordionheader").default
  'AccordionContent': typeof import("primevue/accordioncontent").default
  'AccordionTab': typeof import("primevue/accordiontab").default
  'Card': typeof import("primevue/card").default
  'DeferredContent': typeof import("primevue/deferredcontent").default
  'Divider': typeof import("primevue/divider").default
  'Fieldset': typeof import("primevue/fieldset").default
  'Panel': typeof import("primevue/panel").default
  'ScrollPanel': typeof import("primevue/scrollpanel").default
  'Splitter': typeof import("primevue/splitter").default
  'SplitterPanel': typeof import("primevue/splitterpanel").default
  'Stepper': typeof import("primevue/stepper").default
  'StepList': typeof import("primevue/steplist").default
  'Step': typeof import("primevue/step").default
  'StepItem': typeof import("primevue/stepitem").default
  'StepPanels': typeof import("primevue/steppanels").default
  'StepPanel': typeof import("primevue/steppanel").default
  'TabView': typeof import("primevue/tabview").default
  'Tabs': typeof import("primevue/tabs").default
  'TabList': typeof import("primevue/tablist").default
  'Tab': typeof import("primevue/tab").default
  'TabPanels': typeof import("primevue/tabpanels").default
  'TabPanel': typeof import("primevue/tabpanel").default
  'Toolbar': typeof import("primevue/toolbar").default
  'ConfirmDialog': typeof import("primevue/confirmdialog").default
  'ConfirmPopup': typeof import("primevue/confirmpopup").default
  'Dialog': typeof import("primevue/dialog").default
  'Drawer': typeof import("primevue/drawer").default
  'DynamicDialog': typeof import("primevue/dynamicdialog").default
  'OverlayPanel': typeof import("primevue/overlaypanel").default
  'Popover': typeof import("primevue/popover").default
  'Sidebar': typeof import("primevue/sidebar").default
  'FileUpload': typeof import("primevue/fileupload").default
  'Breadcrumb': typeof import("primevue/breadcrumb").default
  'ContextMenu': typeof import("primevue/contextmenu").default
  'Dock': typeof import("primevue/dock").default
  'Menu': typeof import("primevue/menu").default
  'Menubar': typeof import("primevue/menubar").default
  'MegaMenu': typeof import("primevue/megamenu").default
  'PanelMenu': typeof import("primevue/panelmenu").default
  'Steps': typeof import("primevue/steps").default
  'TabMenu': typeof import("primevue/tabmenu").default
  'TieredMenu': typeof import("primevue/tieredmenu").default
  'Message': typeof import("primevue/message").default
  'InlineMessage': typeof import("primevue/inlinemessage").default
  'Toast': typeof import("primevue/toast").default
  'Carousel': typeof import("primevue/carousel").default
  'Galleria': typeof import("primevue/galleria").default
  'Image': typeof import("primevue/image").default
  'ImageCompare': typeof import("primevue/imagecompare").default
  'Avatar': typeof import("primevue/avatar").default
  'AvatarGroup': typeof import("primevue/avatargroup").default
  'Badge': typeof import("primevue/badge").default
  'BlockUI': typeof import("primevue/blockui").default
  'Chip': typeof import("primevue/chip").default
  'Inplace': typeof import("primevue/inplace").default
  'MeterGroup': typeof import("primevue/metergroup").default
  'OverlayBadge': typeof import("primevue/overlaybadge").default
  'ScrollTop': typeof import("primevue/scrolltop").default
  'Skeleton': typeof import("primevue/skeleton").default
  'ProgressBar': typeof import("primevue/progressbar").default
  'ProgressSpinner': typeof import("primevue/progressspinner").default
  'Tag': typeof import("primevue/tag").default
  'Terminal': typeof import("primevue/terminal").default
  'Form': typeof import("@primevue/forms/form").default
  'FormField': typeof import("@primevue/forms/formfield").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyAppFooter': LazyComponent<typeof import("../../components/AppFooter.vue").default>
  'LazyAppHeader': LazyComponent<typeof import("../../components/AppHeader.vue").default>
  'LazyVoltAccordion': LazyComponent<typeof import("../../components/volt/Accordion.vue").default>
  'LazyVoltAccordionContent': LazyComponent<typeof import("../../components/volt/AccordionContent.vue").default>
  'LazyVoltAccordionHeader': LazyComponent<typeof import("../../components/volt/AccordionHeader.vue").default>
  'LazyVoltAccordionPanel': LazyComponent<typeof import("../../components/volt/AccordionPanel.vue").default>
  'LazyVoltAutoComplete': LazyComponent<typeof import("../../components/volt/AutoComplete.vue").default>
  'LazyVoltAvatar': LazyComponent<typeof import("../../components/volt/Avatar.vue").default>
  'LazyVoltAvatarGroup': LazyComponent<typeof import("../../components/volt/AvatarGroup.vue").default>
  'LazyVoltBadge': LazyComponent<typeof import("../../components/volt/Badge.vue").default>
  'LazyVoltBreadcrumb': LazyComponent<typeof import("../../components/volt/Breadcrumb.vue").default>
  'LazyVoltButton': LazyComponent<typeof import("../../components/volt/Button.vue").default>
  'LazyVoltButtonGroup': LazyComponent<typeof import("../../components/volt/ButtonGroup.vue").default>
  'LazyVoltCard': LazyComponent<typeof import("../../components/volt/Card.vue").default>
  'LazyVoltCheckbox': LazyComponent<typeof import("../../components/volt/Checkbox.vue").default>
  'LazyVoltChip': LazyComponent<typeof import("../../components/volt/Chip.vue").default>
  'LazyVoltConfirmDialog': LazyComponent<typeof import("../../components/volt/ConfirmDialog.vue").default>
  'LazyVoltContrastButton': LazyComponent<typeof import("../../components/volt/ContrastButton.vue").default>
  'LazyVoltDangerButton': LazyComponent<typeof import("../../components/volt/DangerButton.vue").default>
  'LazyVoltDataTable': LazyComponent<typeof import("../../components/volt/DataTable.vue").default>
  'LazyVoltDataView': LazyComponent<typeof import("../../components/volt/DataView.vue").default>
  'LazyVoltDatePicker': LazyComponent<typeof import("../../components/volt/DatePicker.vue").default>
  'LazyVoltDialog': LazyComponent<typeof import("../../components/volt/Dialog.vue").default>
  'LazyVoltDivider': LazyComponent<typeof import("../../components/volt/Divider.vue").default>
  'LazyVoltDrawer': LazyComponent<typeof import("../../components/volt/Drawer.vue").default>
  'LazyVoltFieldset': LazyComponent<typeof import("../../components/volt/Fieldset.vue").default>
  'LazyVoltFluid': LazyComponent<typeof import("../../components/volt/Fluid.vue").default>
  'LazyVoltInplace': LazyComponent<typeof import("../../components/volt/Inplace.vue").default>
  'LazyVoltInputMask': LazyComponent<typeof import("../../components/volt/InputMask.vue").default>
  'LazyVoltInputNumber': LazyComponent<typeof import("../../components/volt/InputNumber.vue").default>
  'LazyVoltInputOtp': LazyComponent<typeof import("../../components/volt/InputOtp.vue").default>
  'LazyVoltInputText': LazyComponent<typeof import("../../components/volt/InputText.vue").default>
  'LazyVoltListbox': LazyComponent<typeof import("../../components/volt/Listbox.vue").default>
  'LazyVoltMenu': LazyComponent<typeof import("../../components/volt/Menu.vue").default>
  'LazyVoltMessage': LazyComponent<typeof import("../../components/volt/Message.vue").default>
  'LazyVoltMeterGroup': LazyComponent<typeof import("../../components/volt/MeterGroup.vue").default>
  'LazyVoltMultiSelect': LazyComponent<typeof import("../../components/volt/MultiSelect.vue").default>
  'LazyVoltOverlayBadge': LazyComponent<typeof import("../../components/volt/OverlayBadge.vue").default>
  'LazyVoltPaginator': LazyComponent<typeof import("../../components/volt/Paginator.vue").default>
  'LazyVoltPanel': LazyComponent<typeof import("../../components/volt/Panel.vue").default>
  'LazyVoltPassword': LazyComponent<typeof import("../../components/volt/Password.vue").default>
  'LazyVoltPopover': LazyComponent<typeof import("../../components/volt/Popover.vue").default>
  'LazyVoltProgressBar': LazyComponent<typeof import("../../components/volt/ProgressBar.vue").default>
  'LazyVoltProgressSpinner': LazyComponent<typeof import("../../components/volt/ProgressSpinner.vue").default>
  'LazyVoltRadioButton': LazyComponent<typeof import("../../components/volt/RadioButton.vue").default>
  'LazyVoltRating': LazyComponent<typeof import("../../components/volt/Rating.vue").default>
  'LazyVoltSecondaryButton': LazyComponent<typeof import("../../components/volt/SecondaryButton.vue").default>
  'LazyVoltSelect': LazyComponent<typeof import("../../components/volt/Select.vue").default>
  'LazyVoltSelectButton': LazyComponent<typeof import("../../components/volt/SelectButton.vue").default>
  'LazyVoltSkeleton': LazyComponent<typeof import("../../components/volt/Skeleton.vue").default>
  'LazyVoltSlider': LazyComponent<typeof import("../../components/volt/Slider.vue").default>
  'LazyVoltSplitter': LazyComponent<typeof import("../../components/volt/Splitter.vue").default>
  'LazyVoltStep': LazyComponent<typeof import("../../components/volt/Step.vue").default>
  'LazyVoltStepItem': LazyComponent<typeof import("../../components/volt/StepItem.vue").default>
  'LazyVoltStepList': LazyComponent<typeof import("../../components/volt/StepList.vue").default>
  'LazyVoltStepPanel': LazyComponent<typeof import("../../components/volt/StepPanel.vue").default>
  'LazyVoltStepPanels': LazyComponent<typeof import("../../components/volt/StepPanels.vue").default>
  'LazyVoltStepper': LazyComponent<typeof import("../../components/volt/Stepper.vue").default>
  'LazyVoltTab': LazyComponent<typeof import("../../components/volt/Tab.vue").default>
  'LazyVoltTabList': LazyComponent<typeof import("../../components/volt/TabList.vue").default>
  'LazyVoltTabPanel': LazyComponent<typeof import("../../components/volt/TabPanel.vue").default>
  'LazyVoltTabPanels': LazyComponent<typeof import("../../components/volt/TabPanels.vue").default>
  'LazyVoltTabs': LazyComponent<typeof import("../../components/volt/Tabs.vue").default>
  'LazyVoltTag': LazyComponent<typeof import("../../components/volt/Tag.vue").default>
  'LazyVoltTextarea': LazyComponent<typeof import("../../components/volt/Textarea.vue").default>
  'LazyVoltTimeline': LazyComponent<typeof import("../../components/volt/Timeline.vue").default>
  'LazyVoltToast': LazyComponent<typeof import("../../components/volt/Toast.vue").default>
  'LazyVoltToggleButton': LazyComponent<typeof import("../../components/volt/ToggleButton.vue").default>
  'LazyVoltToggleSwitch': LazyComponent<typeof import("../../components/volt/ToggleSwitch.vue").default>
  'LazyVoltToolbar': LazyComponent<typeof import("../../components/volt/Toolbar.vue").default>
  'LazyVoltTree': LazyComponent<typeof import("../../components/volt/Tree.vue").default>
  'LazyVoltUtils': LazyComponent<typeof import("../../components/volt/utils").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default>
  'LazyAutoComplete': LazyComponent<typeof import("primevue/autocomplete").default>
  'LazyCalendar': LazyComponent<typeof import("primevue/calendar").default>
  'LazyCascadeSelect': LazyComponent<typeof import("primevue/cascadeselect").default>
  'LazyCheckbox': LazyComponent<typeof import("primevue/checkbox").default>
  'LazyCheckboxGroup': LazyComponent<typeof import("primevue/checkboxgroup").default>
  'LazyChips': LazyComponent<typeof import("primevue/chips").default>
  'LazyColorPicker': LazyComponent<typeof import("primevue/colorpicker").default>
  'LazyDatePicker': LazyComponent<typeof import("primevue/datepicker").default>
  'LazyDropdown': LazyComponent<typeof import("primevue/dropdown").default>
  'LazyFloatLabel': LazyComponent<typeof import("primevue/floatlabel").default>
  'LazyFluid': LazyComponent<typeof import("primevue/fluid").default>
  'LazyIconField': LazyComponent<typeof import("primevue/iconfield").default>
  'LazyIftaLabel': LazyComponent<typeof import("primevue/iftalabel").default>
  'LazyInputChips': LazyComponent<typeof import("primevue/inputchips").default>
  'LazyInputGroup': LazyComponent<typeof import("primevue/inputgroup").default>
  'LazyInputGroupAddon': LazyComponent<typeof import("primevue/inputgroupaddon").default>
  'LazyInputIcon': LazyComponent<typeof import("primevue/inputicon").default>
  'LazyInputMask': LazyComponent<typeof import("primevue/inputmask").default>
  'LazyInputNumber': LazyComponent<typeof import("primevue/inputnumber").default>
  'LazyInputOtp': LazyComponent<typeof import("primevue/inputotp").default>
  'LazyInputSwitch': LazyComponent<typeof import("primevue/inputswitch").default>
  'LazyInputText': LazyComponent<typeof import("primevue/inputtext").default>
  'LazyKnob': LazyComponent<typeof import("primevue/knob").default>
  'LazyListbox': LazyComponent<typeof import("primevue/listbox").default>
  'LazyMultiSelect': LazyComponent<typeof import("primevue/multiselect").default>
  'LazyPassword': LazyComponent<typeof import("primevue/password").default>
  'LazyRadioButton': LazyComponent<typeof import("primevue/radiobutton").default>
  'LazyRadioButtonGroup': LazyComponent<typeof import("primevue/radiobuttongroup").default>
  'LazyRating': LazyComponent<typeof import("primevue/rating").default>
  'LazySelect': LazyComponent<typeof import("primevue/select").default>
  'LazySelectButton': LazyComponent<typeof import("primevue/selectbutton").default>
  'LazySlider': LazyComponent<typeof import("primevue/slider").default>
  'LazyTextarea': LazyComponent<typeof import("primevue/textarea").default>
  'LazyToggleButton': LazyComponent<typeof import("primevue/togglebutton").default>
  'LazyToggleSwitch': LazyComponent<typeof import("primevue/toggleswitch").default>
  'LazyTreeSelect': LazyComponent<typeof import("primevue/treeselect").default>
  'LazyButton': LazyComponent<typeof import("primevue/button").default>
  'LazyButtonGroup': LazyComponent<typeof import("primevue/buttongroup").default>
  'LazySpeedDial': LazyComponent<typeof import("primevue/speeddial").default>
  'LazySplitButton': LazyComponent<typeof import("primevue/splitbutton").default>
  'LazyColumn': LazyComponent<typeof import("primevue/column").default>
  'LazyRow': LazyComponent<typeof import("primevue/row").default>
  'LazyColumnGroup': LazyComponent<typeof import("primevue/columngroup").default>
  'LazyDataTable': LazyComponent<typeof import("primevue/datatable").default>
  'LazyDataView': LazyComponent<typeof import("primevue/dataview").default>
  'LazyOrderList': LazyComponent<typeof import("primevue/orderlist").default>
  'LazyOrganizationChart': LazyComponent<typeof import("primevue/organizationchart").default>
  'LazyPaginator': LazyComponent<typeof import("primevue/paginator").default>
  'LazyPickList': LazyComponent<typeof import("primevue/picklist").default>
  'LazyTree': LazyComponent<typeof import("primevue/tree").default>
  'LazyTreeTable': LazyComponent<typeof import("primevue/treetable").default>
  'LazyTimeline': LazyComponent<typeof import("primevue/timeline").default>
  'LazyVirtualScroller': LazyComponent<typeof import("primevue/virtualscroller").default>
  'LazyAccordion': LazyComponent<typeof import("primevue/accordion").default>
  'LazyAccordionPanel': LazyComponent<typeof import("primevue/accordionpanel").default>
  'LazyAccordionHeader': LazyComponent<typeof import("primevue/accordionheader").default>
  'LazyAccordionContent': LazyComponent<typeof import("primevue/accordioncontent").default>
  'LazyAccordionTab': LazyComponent<typeof import("primevue/accordiontab").default>
  'LazyCard': LazyComponent<typeof import("primevue/card").default>
  'LazyDeferredContent': LazyComponent<typeof import("primevue/deferredcontent").default>
  'LazyDivider': LazyComponent<typeof import("primevue/divider").default>
  'LazyFieldset': LazyComponent<typeof import("primevue/fieldset").default>
  'LazyPanel': LazyComponent<typeof import("primevue/panel").default>
  'LazyScrollPanel': LazyComponent<typeof import("primevue/scrollpanel").default>
  'LazySplitter': LazyComponent<typeof import("primevue/splitter").default>
  'LazySplitterPanel': LazyComponent<typeof import("primevue/splitterpanel").default>
  'LazyStepper': LazyComponent<typeof import("primevue/stepper").default>
  'LazyStepList': LazyComponent<typeof import("primevue/steplist").default>
  'LazyStep': LazyComponent<typeof import("primevue/step").default>
  'LazyStepItem': LazyComponent<typeof import("primevue/stepitem").default>
  'LazyStepPanels': LazyComponent<typeof import("primevue/steppanels").default>
  'LazyStepPanel': LazyComponent<typeof import("primevue/steppanel").default>
  'LazyTabView': LazyComponent<typeof import("primevue/tabview").default>
  'LazyTabs': LazyComponent<typeof import("primevue/tabs").default>
  'LazyTabList': LazyComponent<typeof import("primevue/tablist").default>
  'LazyTab': LazyComponent<typeof import("primevue/tab").default>
  'LazyTabPanels': LazyComponent<typeof import("primevue/tabpanels").default>
  'LazyTabPanel': LazyComponent<typeof import("primevue/tabpanel").default>
  'LazyToolbar': LazyComponent<typeof import("primevue/toolbar").default>
  'LazyConfirmDialog': LazyComponent<typeof import("primevue/confirmdialog").default>
  'LazyConfirmPopup': LazyComponent<typeof import("primevue/confirmpopup").default>
  'LazyDialog': LazyComponent<typeof import("primevue/dialog").default>
  'LazyDrawer': LazyComponent<typeof import("primevue/drawer").default>
  'LazyDynamicDialog': LazyComponent<typeof import("primevue/dynamicdialog").default>
  'LazyOverlayPanel': LazyComponent<typeof import("primevue/overlaypanel").default>
  'LazyPopover': LazyComponent<typeof import("primevue/popover").default>
  'LazySidebar': LazyComponent<typeof import("primevue/sidebar").default>
  'LazyFileUpload': LazyComponent<typeof import("primevue/fileupload").default>
  'LazyBreadcrumb': LazyComponent<typeof import("primevue/breadcrumb").default>
  'LazyContextMenu': LazyComponent<typeof import("primevue/contextmenu").default>
  'LazyDock': LazyComponent<typeof import("primevue/dock").default>
  'LazyMenu': LazyComponent<typeof import("primevue/menu").default>
  'LazyMenubar': LazyComponent<typeof import("primevue/menubar").default>
  'LazyMegaMenu': LazyComponent<typeof import("primevue/megamenu").default>
  'LazyPanelMenu': LazyComponent<typeof import("primevue/panelmenu").default>
  'LazySteps': LazyComponent<typeof import("primevue/steps").default>
  'LazyTabMenu': LazyComponent<typeof import("primevue/tabmenu").default>
  'LazyTieredMenu': LazyComponent<typeof import("primevue/tieredmenu").default>
  'LazyMessage': LazyComponent<typeof import("primevue/message").default>
  'LazyInlineMessage': LazyComponent<typeof import("primevue/inlinemessage").default>
  'LazyToast': LazyComponent<typeof import("primevue/toast").default>
  'LazyCarousel': LazyComponent<typeof import("primevue/carousel").default>
  'LazyGalleria': LazyComponent<typeof import("primevue/galleria").default>
  'LazyImage': LazyComponent<typeof import("primevue/image").default>
  'LazyImageCompare': LazyComponent<typeof import("primevue/imagecompare").default>
  'LazyAvatar': LazyComponent<typeof import("primevue/avatar").default>
  'LazyAvatarGroup': LazyComponent<typeof import("primevue/avatargroup").default>
  'LazyBadge': LazyComponent<typeof import("primevue/badge").default>
  'LazyBlockUI': LazyComponent<typeof import("primevue/blockui").default>
  'LazyChip': LazyComponent<typeof import("primevue/chip").default>
  'LazyInplace': LazyComponent<typeof import("primevue/inplace").default>
  'LazyMeterGroup': LazyComponent<typeof import("primevue/metergroup").default>
  'LazyOverlayBadge': LazyComponent<typeof import("primevue/overlaybadge").default>
  'LazyScrollTop': LazyComponent<typeof import("primevue/scrolltop").default>
  'LazySkeleton': LazyComponent<typeof import("primevue/skeleton").default>
  'LazyProgressBar': LazyComponent<typeof import("primevue/progressbar").default>
  'LazyProgressSpinner': LazyComponent<typeof import("primevue/progressspinner").default>
  'LazyTag': LazyComponent<typeof import("primevue/tag").default>
  'LazyTerminal': LazyComponent<typeof import("primevue/terminal").default>
  'LazyForm': LazyComponent<typeof import("@primevue/forms/form").default>
  'LazyFormField': LazyComponent<typeof import("@primevue/forms/formfield").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
