import { eq } from "drizzle-orm"
import bcrypt from "bcryptjs"
import { db } from "~/lib/external/drizzle/drizzle"
import { users } from "~/lib/external/drizzle/migrations/schema"
import { userPublicSelect } from "~/lib/utils/queries/users"
import { logger } from "~/lib/logger/logger"
import type { ApiResponse } from "~/types/api"
import type { UserPublic } from "~/types/users"
import { z } from "zod"
import { ok, fail } from "~/server/utils/api-response"
import { readZodBody } from "~/server/utils/validate"

export default defineEventHandler(async (event): Promise<ApiResponse<UserPublic>> => {
  try {
    const body = await readBody(event)
    const rawEmail = typeof body?.email === "string" ? body.email : ""
    const rawPassword = typeof body?.password === "string" ? body.password : ""

    if (!rawEmail) {
      logger.debug("Registration attempt without email")
      return fail(event, 400, { en: "Email is required", vi: "Email là bắt buộc" }) as ApiResponse<UserPublic>
    }

    if (!rawPassword) {
      logger.debug("Registration attempt without password", { email: rawEmail })
      return fail(event, 400, { en: "Password is required", vi: "Mật khẩu là bắt buộc" }) as ApiResponse<UserPublic>
    }

    const RegisterBodySchema = z.object({
      email: z.email().trim().toLowerCase(),
      password: z.string().min(1),
      fullName: z.string().trim().min(1),
    })

    const validated = await readZodBody(event, RegisterBodySchema)
    if (!validated.success) {
      return fail(event, 400, { en: "Invalid input data", vi: "Dữ liệu đầu vào không hợp lệ" }) as ApiResponse<UserPublic>
    }

    const { email, password, fullName } = validated.data

    // Check email uniqueness
    const existingUser = await db
      .select({
        vpfId: users.vpfId,
      })
      .from(users)
      .where(eq(users.email, email))
      .limit(1)
      .then((rows) => rows[0])

    if (existingUser) {
      logger.debug("Registration attempt with existing email", { email })
      return fail(event, 409, { en: "Email already exists", vi: "Email đã tồn tại" }) as ApiResponse<UserPublic>
    }

    // Hash password
    const saltRounds = 10
    const hashedPassword = await bcrypt.hash(password, saltRounds)

    // Insert new user
    // Note: vpfId will be auto-generated by the database
    const insertResult = await db
      .insert(users)
      .values({
        email,
        password: hashedPassword,
        fullName: fullName,
      })
      .returning({
        vpfId: users.vpfId,
      })
      .then((rows) => rows[0])

    if (!insertResult) {
      logger.error("Failed to create user", { email })
      return fail(event, 500, { en: "Failed to create user", vi: "Không thể tạo người dùng" }) as ApiResponse<UserPublic>
    }

    // Query the newly created user with public select
    const [userPublic] = await db
      .select(userPublicSelect)
      .from(users)
      .where(eq(users.vpfId, insertResult.vpfId))
      .limit(1)

    if (!userPublic) {
      logger.error("Failed to fetch user public data after registration", { vpfId: insertResult.vpfId })
      return fail(event, 500, { en: "Failed to create user", vi: "Không thể tạo người dùng" }) as ApiResponse<UserPublic>
    }

    logger.info("User registered successfully", { vpfId: insertResult.vpfId, email })

    return ok(userPublic, { en: "Registration successful", vi: "Đăng ký thành công" })
  } catch (error) {
    logger.error("Registration error", { error: (error as Error).message })

    // Check if it's a unique constraint violation
    if (error instanceof Error && error.message.includes("unique")) {
      return fail(event, 409, { en: "Email already exists", vi: "Email đã tồn tại" }) as ApiResponse<UserPublic>
    }

    return fail(event, 500, { en: "An error occurred during registration", vi: "Đã xảy ra lỗi khi đăng ký" }) as ApiResponse<UserPublic>
  }
})
