import { eq } from "drizzle-orm"
import bcrypt from "bcryptjs"
import { db } from "~/lib/external/drizzle/drizzle"
import { users } from "~/lib/external/drizzle/migrations/schema"
import { userPublicSelect } from "~/lib/external/drizzle/migrations/queries"
import { logger } from "~/lib/logger/logger"
import type { ApiResponse } from "~/types/api"
import type { UserPublic } from "~/types/users"

export default defineEventHandler(async (event): Promise<ApiResponse<UserPublic>> => {
  try {
    const body = await readBody(event)
    const { email, password, fullName } = body

    // Validate input
    if (!email) {
      logger.debug("Registration attempt without email")
      setResponseStatus(event, 400)
      return {
        success: false,
        data: null,
        message: {
          en: "Email is required",
          vi: "Email là bắt buộc",
        },
      }
    }

    if (!password) {
      logger.debug("Registration attempt without password", { email })
      setResponseStatus(event, 400)
      return {
        success: false,
        data: null,
        message: {
          en: "Password is required",
          vi: "Mật khẩu là bắt buộc",
        },
      }
    }

    // Validate email format (basic validation)
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      logger.debug("Registration attempt with invalid email format", { email })
      setResponseStatus(event, 400)
      return {
        success: false,
        data: null,
        message: {
          en: "Invalid email format",
          vi: "Định dạng email không hợp lệ",
        },
      }
    }

    // Check email uniqueness
    const existingUser = await db
      .select({
        vpfId: users.vpfId,
      })
      .from(users)
      .where(eq(users.email, email))
      .limit(1)
      .then((rows) => rows[0])

    if (existingUser) {
      logger.debug("Registration attempt with existing email", { email })
      setResponseStatus(event, 409)
      return {
        success: false,
        data: null,
        message: {
          en: "Email already exists",
          vi: "Email đã tồn tại",
        },
      }
    }

    // Hash password
    const saltRounds = 10
    const hashedPassword = await bcrypt.hash(password, saltRounds)

    // Insert new user
    // Note: vpfId will be auto-generated by the database
    const insertResult = await db
      .insert(users)
      .values({
        email,
        password: hashedPassword,
        fullName: fullName,
        active: true,
      })
      .returning({
        vpfId: users.vpfId,
      })
      .then((rows) => rows[0])

    if (!insertResult) {
      logger.error("Failed to create user", { email })
      setResponseStatus(event, 500)
      return {
        success: false,
        data: null,
        message: {
          en: "Failed to create user",
          vi: "Không thể tạo người dùng",
        },
      }
    }

    // Query the newly created user with public select
    const [userPublic] = await db
      .select(userPublicSelect)
      .from(users)
      .where(eq(users.vpfId, insertResult.vpfId))
      .limit(1)

    if (!userPublic) {
      logger.error("Failed to fetch user public data after registration", { vpfId: insertResult.vpfId })
      setResponseStatus(event, 500)
      return {
        success: false,
        data: null,
        message: {
          en: "Failed to create user",
          vi: "Không thể tạo người dùng",
        },
      }
    }

    logger.info("User registered successfully", { vpfId: insertResult.vpfId, email })

    setResponseStatus(event, 200)
    return {
      success: true,
      data: userPublic,
      message: {
        en: "Registration successful",
        vi: "Đăng ký thành công",
      },
    }
  } catch (error) {
    logger.error("Registration error", { error: (error as Error).message })

    // Check if it's a unique constraint violation
    if (error instanceof Error && error.message.includes("unique")) {
      setResponseStatus(event, 409)
      return {
        success: false,
        data: null,
        message: {
          en: "Email already exists",
          vi: "Email đã tồn tại",
        },
      }
    }

    setResponseStatus(event, 500)
    return {
      success: false,
      data: null,
      message: {
        en: "An error occurred during registration",
        vi: "Đã xảy ra lỗi khi đăng ký",
      },
    }
  }
})
