import { eq } from "drizzle-orm"
import bcrypt from "bcryptjs"
import { db } from "~/lib/external/drizzle/drizzle"
import { users } from "~/lib/external/drizzle/migrations/schema"
import { userPublicSelect } from "~/lib/utils/queries/users"
import { logger } from "~/lib/logger/logger"
import { config } from "~/lib/config/config"
import { signToken } from "~/lib/utils/jwt"
import { sendVerificationCodeEmail } from "~/lib/utils/email"
import type { ApiResponse, RegisterResponse } from "~/types/api"
import { z } from "zod"
import { ok, fail } from "~/server/utils/api-response"
import { readZodBody } from "~/server/utils/validate"
import { setAuthCookie } from "~/server/utils/auth-cookie"

/** Verification codes are valid for 30 minutes. */
const VERIFICATION_CODE_TTL_MS = 30 * 60 * 1000

function generateVerificationCode(): string {
  return String(Math.floor(100000 + Math.random() * 900000))
}

export default defineEventHandler(async (event): Promise<ApiResponse<RegisterResponse>> => {
  try {
    const body = await readBody(event)
    const rawEmail = typeof body?.email === "string" ? body.email : ""
    const rawPassword = typeof body?.password === "string" ? body.password : ""

    if (!rawEmail) {
      logger.debug("Registration attempt without email")
      return fail(event, 400, { en: "Email is required", vi: "Email là bắt buộc" }) as ApiResponse<RegisterResponse>
    }

    if (!rawPassword) {
      logger.debug("Registration attempt without password", { email: rawEmail })
      return fail(event, 400, { en: "Password is required", vi: "Mật khẩu là bắt buộc" }) as ApiResponse<RegisterResponse>
    }

    const RegisterBodySchema = z.object({
      email: z.email().trim().toLowerCase(),
      password: z.string().min(8),
      // Optional at registration; the athlete provides their real name in the verification form.
      fullName: z.string().trim().min(1).optional(),
    })

    const validated = await readZodBody(event, RegisterBodySchema)
    if (!validated.success) {
      return fail(event, 400, { en: "Invalid input data", vi: "Dữ liệu đầu vào không hợp lệ" }) as ApiResponse<RegisterResponse>
    }

    const { email, password } = validated.data
    // Default the display name to the email local-part when not supplied.
    const fullName = validated.data.fullName || email.split("@")[0]

    // Check email uniqueness
    const existingUser = await db
      .select({
        vpfId: users.vpfId,
      })
      .from(users)
      .where(eq(users.email, email))
      .limit(1)
      .then((rows) => rows[0])

    if (existingUser) {
      logger.debug("Registration attempt with existing email", { email })
      return fail(event, 409, { en: "Email already exists", vi: "Email đã tồn tại" }) as ApiResponse<RegisterResponse>
    }

    // Hash password
    const saltRounds = 10
    const hashedPassword = await bcrypt.hash(password, saltRounds)

    // When verification is skipped (dev), mark the account verified and send no code.
    const skipVerification = config.emailVerificationSkip
    const code = skipVerification ? null : generateVerificationCode()
    const expiresAt = skipVerification ? null : new Date(Date.now() + VERIFICATION_CODE_TTL_MS).toISOString()

    // Insert new user. vpfId is auto-generated by the database.
    const insertResult = await db
      .insert(users)
      .values({
        email,
        password: hashedPassword,
        fullName,
        emailVerified: skipVerification,
        emailVerificationCode: code,
        emailVerificationExpiresAt: expiresAt,
      })
      .returning({
        vpfId: users.vpfId,
        role: users.role,
      })
      .then((rows) => rows[0])

    if (!insertResult) {
      logger.error("Failed to create user", { email })
      return fail(event, 500, { en: "Failed to create user", vi: "Không thể tạo người dùng" }) as ApiResponse<RegisterResponse>
    }

    // Query the newly created user with public select
    const [userPublic] = await db
      .select(userPublicSelect)
      .from(users)
      .where(eq(users.vpfId, insertResult.vpfId))
      .limit(1)

    if (!userPublic) {
      logger.error("Failed to fetch user public data after registration", { vpfId: insertResult.vpfId })
      return fail(event, 500, { en: "Failed to create user", vi: "Không thể tạo người dùng" }) as ApiResponse<RegisterResponse>
    }

    if (skipVerification) {
      logger.warn("Email verification skipped for new registration (EMAIL_VERIFICATION_SKIP enabled)", { email })
    } else if (code) {
      await sendVerificationCodeEmail(email, code)
    }

    // Auto-login: issue a token so the athlete can proceed to email/identity verification.
    const token = signToken({
      vpfId: insertResult.vpfId,
      email,
      role: insertResult.role,
    })
    setAuthCookie(event, token)

    logger.info("User registered successfully", { vpfId: insertResult.vpfId, email, emailVerified: skipVerification })

    return ok(
      { user: userPublic, token, emailVerified: skipVerification },
      { en: "Registration successful", vi: "Đăng ký thành công" },
    )
  } catch (error) {
    logger.error("Registration error", { error: (error as Error).message })

    // Check if it's a unique constraint violation
    if (error instanceof Error && error.message.includes("unique")) {
      return fail(event, 409, { en: "Email already exists", vi: "Email đã tồn tại" }) as ApiResponse<RegisterResponse>
    }

    return fail(event, 500, { en: "An error occurred during registration", vi: "Đã xảy ra lỗi khi đăng ký" }) as ApiResponse<RegisterResponse>
  }
})
