// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/7/2026, 11:34:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/whiteou7/vpf-page/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/plugins/**/*.{js,ts,mjs}","/home/whiteou7/vpf-page/composables/**/*.{js,ts,mjs}","/home/whiteou7/vpf-page/utils/**/*.{js,ts,mjs}","/home/whiteou7/vpf-page/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/whiteou7/vpf-page/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;