
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppFooter: typeof import("../components/AppFooter.vue").default
export const AppHeader: typeof import("../components/AppHeader.vue").default
export const VoltAccordion: typeof import("../components/volt/Accordion.vue").default
export const VoltAccordionContent: typeof import("../components/volt/AccordionContent.vue").default
export const VoltAccordionHeader: typeof import("../components/volt/AccordionHeader.vue").default
export const VoltAccordionPanel: typeof import("../components/volt/AccordionPanel.vue").default
export const VoltAutoComplete: typeof import("../components/volt/AutoComplete.vue").default
export const VoltAvatar: typeof import("../components/volt/Avatar.vue").default
export const VoltAvatarGroup: typeof import("../components/volt/AvatarGroup.vue").default
export const VoltBadge: typeof import("../components/volt/Badge.vue").default
export const VoltBreadcrumb: typeof import("../components/volt/Breadcrumb.vue").default
export const VoltButton: typeof import("../components/volt/Button.vue").default
export const VoltButtonGroup: typeof import("../components/volt/ButtonGroup.vue").default
export const VoltCard: typeof import("../components/volt/Card.vue").default
export const VoltCheckbox: typeof import("../components/volt/Checkbox.vue").default
export const VoltChip: typeof import("../components/volt/Chip.vue").default
export const VoltConfirmDialog: typeof import("../components/volt/ConfirmDialog.vue").default
export const VoltContrastButton: typeof import("../components/volt/ContrastButton.vue").default
export const VoltDangerButton: typeof import("../components/volt/DangerButton.vue").default
export const VoltDataTable: typeof import("../components/volt/DataTable.vue").default
export const VoltDataView: typeof import("../components/volt/DataView.vue").default
export const VoltDatePicker: typeof import("../components/volt/DatePicker.vue").default
export const VoltDialog: typeof import("../components/volt/Dialog.vue").default
export const VoltDivider: typeof import("../components/volt/Divider.vue").default
export const VoltDrawer: typeof import("../components/volt/Drawer.vue").default
export const VoltFieldset: typeof import("../components/volt/Fieldset.vue").default
export const VoltFluid: typeof import("../components/volt/Fluid.vue").default
export const VoltInplace: typeof import("../components/volt/Inplace.vue").default
export const VoltInputMask: typeof import("../components/volt/InputMask.vue").default
export const VoltInputNumber: typeof import("../components/volt/InputNumber.vue").default
export const VoltInputOtp: typeof import("../components/volt/InputOtp.vue").default
export const VoltInputText: typeof import("../components/volt/InputText.vue").default
export const VoltListbox: typeof import("../components/volt/Listbox.vue").default
export const VoltMenu: typeof import("../components/volt/Menu.vue").default
export const VoltMessage: typeof import("../components/volt/Message.vue").default
export const VoltMeterGroup: typeof import("../components/volt/MeterGroup.vue").default
export const VoltMultiSelect: typeof import("../components/volt/MultiSelect.vue").default
export const VoltOverlayBadge: typeof import("../components/volt/OverlayBadge.vue").default
export const VoltPaginator: typeof import("../components/volt/Paginator.vue").default
export const VoltPanel: typeof import("../components/volt/Panel.vue").default
export const VoltPassword: typeof import("../components/volt/Password.vue").default
export const VoltPopover: typeof import("../components/volt/Popover.vue").default
export const VoltProgressBar: typeof import("../components/volt/ProgressBar.vue").default
export const VoltProgressSpinner: typeof import("../components/volt/ProgressSpinner.vue").default
export const VoltRadioButton: typeof import("../components/volt/RadioButton.vue").default
export const VoltRating: typeof import("../components/volt/Rating.vue").default
export const VoltSecondaryButton: typeof import("../components/volt/SecondaryButton.vue").default
export const VoltSelect: typeof import("../components/volt/Select.vue").default
export const VoltSelectButton: typeof import("../components/volt/SelectButton.vue").default
export const VoltSkeleton: typeof import("../components/volt/Skeleton.vue").default
export const VoltSlider: typeof import("../components/volt/Slider.vue").default
export const VoltSplitter: typeof import("../components/volt/Splitter.vue").default
export const VoltStep: typeof import("../components/volt/Step.vue").default
export const VoltStepItem: typeof import("../components/volt/StepItem.vue").default
export const VoltStepList: typeof import("../components/volt/StepList.vue").default
export const VoltStepPanel: typeof import("../components/volt/StepPanel.vue").default
export const VoltStepPanels: typeof import("../components/volt/StepPanels.vue").default
export const VoltStepper: typeof import("../components/volt/Stepper.vue").default
export const VoltTab: typeof import("../components/volt/Tab.vue").default
export const VoltTabList: typeof import("../components/volt/TabList.vue").default
export const VoltTabPanel: typeof import("../components/volt/TabPanel.vue").default
export const VoltTabPanels: typeof import("../components/volt/TabPanels.vue").default
export const VoltTabs: typeof import("../components/volt/Tabs.vue").default
export const VoltTag: typeof import("../components/volt/Tag.vue").default
export const VoltTextarea: typeof import("../components/volt/Textarea.vue").default
export const VoltTimeline: typeof import("../components/volt/Timeline.vue").default
export const VoltToast: typeof import("../components/volt/Toast.vue").default
export const VoltToggleButton: typeof import("../components/volt/ToggleButton.vue").default
export const VoltToggleSwitch: typeof import("../components/volt/ToggleSwitch.vue").default
export const VoltToolbar: typeof import("../components/volt/Toolbar.vue").default
export const VoltTree: typeof import("../components/volt/Tree.vue").default
export const VoltUtils: typeof import("../components/volt/utils").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default
export const AutoComplete: typeof import("primevue/autocomplete").default
export const Calendar: typeof import("primevue/calendar").default
export const CascadeSelect: typeof import("primevue/cascadeselect").default
export const Checkbox: typeof import("primevue/checkbox").default
export const CheckboxGroup: typeof import("primevue/checkboxgroup").default
export const Chips: typeof import("primevue/chips").default
export const ColorPicker: typeof import("primevue/colorpicker").default
export const DatePicker: typeof import("primevue/datepicker").default
export const Dropdown: typeof import("primevue/dropdown").default
export const FloatLabel: typeof import("primevue/floatlabel").default
export const Fluid: typeof import("primevue/fluid").default
export const IconField: typeof import("primevue/iconfield").default
export const IftaLabel: typeof import("primevue/iftalabel").default
export const InputChips: typeof import("primevue/inputchips").default
export const InputGroup: typeof import("primevue/inputgroup").default
export const InputGroupAddon: typeof import("primevue/inputgroupaddon").default
export const InputIcon: typeof import("primevue/inputicon").default
export const InputMask: typeof import("primevue/inputmask").default
export const InputNumber: typeof import("primevue/inputnumber").default
export const InputOtp: typeof import("primevue/inputotp").default
export const InputSwitch: typeof import("primevue/inputswitch").default
export const InputText: typeof import("primevue/inputtext").default
export const Knob: typeof import("primevue/knob").default
export const Listbox: typeof import("primevue/listbox").default
export const MultiSelect: typeof import("primevue/multiselect").default
export const Password: typeof import("primevue/password").default
export const RadioButton: typeof import("primevue/radiobutton").default
export const RadioButtonGroup: typeof import("primevue/radiobuttongroup").default
export const Rating: typeof import("primevue/rating").default
export const Select: typeof import("primevue/select").default
export const SelectButton: typeof import("primevue/selectbutton").default
export const Slider: typeof import("primevue/slider").default
export const Textarea: typeof import("primevue/textarea").default
export const ToggleButton: typeof import("primevue/togglebutton").default
export const ToggleSwitch: typeof import("primevue/toggleswitch").default
export const TreeSelect: typeof import("primevue/treeselect").default
export const Button: typeof import("primevue/button").default
export const ButtonGroup: typeof import("primevue/buttongroup").default
export const SpeedDial: typeof import("primevue/speeddial").default
export const SplitButton: typeof import("primevue/splitbutton").default
export const Column: typeof import("primevue/column").default
export const Row: typeof import("primevue/row").default
export const ColumnGroup: typeof import("primevue/columngroup").default
export const DataTable: typeof import("primevue/datatable").default
export const DataView: typeof import("primevue/dataview").default
export const OrderList: typeof import("primevue/orderlist").default
export const OrganizationChart: typeof import("primevue/organizationchart").default
export const Paginator: typeof import("primevue/paginator").default
export const PickList: typeof import("primevue/picklist").default
export const Tree: typeof import("primevue/tree").default
export const TreeTable: typeof import("primevue/treetable").default
export const Timeline: typeof import("primevue/timeline").default
export const VirtualScroller: typeof import("primevue/virtualscroller").default
export const Accordion: typeof import("primevue/accordion").default
export const AccordionPanel: typeof import("primevue/accordionpanel").default
export const AccordionHeader: typeof import("primevue/accordionheader").default
export const AccordionContent: typeof import("primevue/accordioncontent").default
export const AccordionTab: typeof import("primevue/accordiontab").default
export const Card: typeof import("primevue/card").default
export const DeferredContent: typeof import("primevue/deferredcontent").default
export const Divider: typeof import("primevue/divider").default
export const Fieldset: typeof import("primevue/fieldset").default
export const Panel: typeof import("primevue/panel").default
export const ScrollPanel: typeof import("primevue/scrollpanel").default
export const Splitter: typeof import("primevue/splitter").default
export const SplitterPanel: typeof import("primevue/splitterpanel").default
export const Stepper: typeof import("primevue/stepper").default
export const StepList: typeof import("primevue/steplist").default
export const Step: typeof import("primevue/step").default
export const StepItem: typeof import("primevue/stepitem").default
export const StepPanels: typeof import("primevue/steppanels").default
export const StepPanel: typeof import("primevue/steppanel").default
export const TabView: typeof import("primevue/tabview").default
export const Tabs: typeof import("primevue/tabs").default
export const TabList: typeof import("primevue/tablist").default
export const Tab: typeof import("primevue/tab").default
export const TabPanels: typeof import("primevue/tabpanels").default
export const TabPanel: typeof import("primevue/tabpanel").default
export const Toolbar: typeof import("primevue/toolbar").default
export const ConfirmDialog: typeof import("primevue/confirmdialog").default
export const ConfirmPopup: typeof import("primevue/confirmpopup").default
export const Dialog: typeof import("primevue/dialog").default
export const Drawer: typeof import("primevue/drawer").default
export const DynamicDialog: typeof import("primevue/dynamicdialog").default
export const OverlayPanel: typeof import("primevue/overlaypanel").default
export const Popover: typeof import("primevue/popover").default
export const Sidebar: typeof import("primevue/sidebar").default
export const FileUpload: typeof import("primevue/fileupload").default
export const Breadcrumb: typeof import("primevue/breadcrumb").default
export const ContextMenu: typeof import("primevue/contextmenu").default
export const Dock: typeof import("primevue/dock").default
export const Menu: typeof import("primevue/menu").default
export const Menubar: typeof import("primevue/menubar").default
export const MegaMenu: typeof import("primevue/megamenu").default
export const PanelMenu: typeof import("primevue/panelmenu").default
export const Steps: typeof import("primevue/steps").default
export const TabMenu: typeof import("primevue/tabmenu").default
export const TieredMenu: typeof import("primevue/tieredmenu").default
export const Message: typeof import("primevue/message").default
export const InlineMessage: typeof import("primevue/inlinemessage").default
export const Toast: typeof import("primevue/toast").default
export const Carousel: typeof import("primevue/carousel").default
export const Galleria: typeof import("primevue/galleria").default
export const Image: typeof import("primevue/image").default
export const ImageCompare: typeof import("primevue/imagecompare").default
export const Avatar: typeof import("primevue/avatar").default
export const AvatarGroup: typeof import("primevue/avatargroup").default
export const Badge: typeof import("primevue/badge").default
export const BlockUI: typeof import("primevue/blockui").default
export const Chip: typeof import("primevue/chip").default
export const Inplace: typeof import("primevue/inplace").default
export const MeterGroup: typeof import("primevue/metergroup").default
export const OverlayBadge: typeof import("primevue/overlaybadge").default
export const ScrollTop: typeof import("primevue/scrolltop").default
export const Skeleton: typeof import("primevue/skeleton").default
export const ProgressBar: typeof import("primevue/progressbar").default
export const ProgressSpinner: typeof import("primevue/progressspinner").default
export const Tag: typeof import("primevue/tag").default
export const Terminal: typeof import("primevue/terminal").default
export const Form: typeof import("@primevue/forms/form").default
export const FormField: typeof import("@primevue/forms/formfield").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyAppFooter: LazyComponent<typeof import("../components/AppFooter.vue").default>
export const LazyAppHeader: LazyComponent<typeof import("../components/AppHeader.vue").default>
export const LazyVoltAccordion: LazyComponent<typeof import("../components/volt/Accordion.vue").default>
export const LazyVoltAccordionContent: LazyComponent<typeof import("../components/volt/AccordionContent.vue").default>
export const LazyVoltAccordionHeader: LazyComponent<typeof import("../components/volt/AccordionHeader.vue").default>
export const LazyVoltAccordionPanel: LazyComponent<typeof import("../components/volt/AccordionPanel.vue").default>
export const LazyVoltAutoComplete: LazyComponent<typeof import("../components/volt/AutoComplete.vue").default>
export const LazyVoltAvatar: LazyComponent<typeof import("../components/volt/Avatar.vue").default>
export const LazyVoltAvatarGroup: LazyComponent<typeof import("../components/volt/AvatarGroup.vue").default>
export const LazyVoltBadge: LazyComponent<typeof import("../components/volt/Badge.vue").default>
export const LazyVoltBreadcrumb: LazyComponent<typeof import("../components/volt/Breadcrumb.vue").default>
export const LazyVoltButton: LazyComponent<typeof import("../components/volt/Button.vue").default>
export const LazyVoltButtonGroup: LazyComponent<typeof import("../components/volt/ButtonGroup.vue").default>
export const LazyVoltCard: LazyComponent<typeof import("../components/volt/Card.vue").default>
export const LazyVoltCheckbox: LazyComponent<typeof import("../components/volt/Checkbox.vue").default>
export const LazyVoltChip: LazyComponent<typeof import("../components/volt/Chip.vue").default>
export const LazyVoltConfirmDialog: LazyComponent<typeof import("../components/volt/ConfirmDialog.vue").default>
export const LazyVoltContrastButton: LazyComponent<typeof import("../components/volt/ContrastButton.vue").default>
export const LazyVoltDangerButton: LazyComponent<typeof import("../components/volt/DangerButton.vue").default>
export const LazyVoltDataTable: LazyComponent<typeof import("../components/volt/DataTable.vue").default>
export const LazyVoltDataView: LazyComponent<typeof import("../components/volt/DataView.vue").default>
export const LazyVoltDatePicker: LazyComponent<typeof import("../components/volt/DatePicker.vue").default>
export const LazyVoltDialog: LazyComponent<typeof import("../components/volt/Dialog.vue").default>
export const LazyVoltDivider: LazyComponent<typeof import("../components/volt/Divider.vue").default>
export const LazyVoltDrawer: LazyComponent<typeof import("../components/volt/Drawer.vue").default>
export const LazyVoltFieldset: LazyComponent<typeof import("../components/volt/Fieldset.vue").default>
export const LazyVoltFluid: LazyComponent<typeof import("../components/volt/Fluid.vue").default>
export const LazyVoltInplace: LazyComponent<typeof import("../components/volt/Inplace.vue").default>
export const LazyVoltInputMask: LazyComponent<typeof import("../components/volt/InputMask.vue").default>
export const LazyVoltInputNumber: LazyComponent<typeof import("../components/volt/InputNumber.vue").default>
export const LazyVoltInputOtp: LazyComponent<typeof import("../components/volt/InputOtp.vue").default>
export const LazyVoltInputText: LazyComponent<typeof import("../components/volt/InputText.vue").default>
export const LazyVoltListbox: LazyComponent<typeof import("../components/volt/Listbox.vue").default>
export const LazyVoltMenu: LazyComponent<typeof import("../components/volt/Menu.vue").default>
export const LazyVoltMessage: LazyComponent<typeof import("../components/volt/Message.vue").default>
export const LazyVoltMeterGroup: LazyComponent<typeof import("../components/volt/MeterGroup.vue").default>
export const LazyVoltMultiSelect: LazyComponent<typeof import("../components/volt/MultiSelect.vue").default>
export const LazyVoltOverlayBadge: LazyComponent<typeof import("../components/volt/OverlayBadge.vue").default>
export const LazyVoltPaginator: LazyComponent<typeof import("../components/volt/Paginator.vue").default>
export const LazyVoltPanel: LazyComponent<typeof import("../components/volt/Panel.vue").default>
export const LazyVoltPassword: LazyComponent<typeof import("../components/volt/Password.vue").default>
export const LazyVoltPopover: LazyComponent<typeof import("../components/volt/Popover.vue").default>
export const LazyVoltProgressBar: LazyComponent<typeof import("../components/volt/ProgressBar.vue").default>
export const LazyVoltProgressSpinner: LazyComponent<typeof import("../components/volt/ProgressSpinner.vue").default>
export const LazyVoltRadioButton: LazyComponent<typeof import("../components/volt/RadioButton.vue").default>
export const LazyVoltRating: LazyComponent<typeof import("../components/volt/Rating.vue").default>
export const LazyVoltSecondaryButton: LazyComponent<typeof import("../components/volt/SecondaryButton.vue").default>
export const LazyVoltSelect: LazyComponent<typeof import("../components/volt/Select.vue").default>
export const LazyVoltSelectButton: LazyComponent<typeof import("../components/volt/SelectButton.vue").default>
export const LazyVoltSkeleton: LazyComponent<typeof import("../components/volt/Skeleton.vue").default>
export const LazyVoltSlider: LazyComponent<typeof import("../components/volt/Slider.vue").default>
export const LazyVoltSplitter: LazyComponent<typeof import("../components/volt/Splitter.vue").default>
export const LazyVoltStep: LazyComponent<typeof import("../components/volt/Step.vue").default>
export const LazyVoltStepItem: LazyComponent<typeof import("../components/volt/StepItem.vue").default>
export const LazyVoltStepList: LazyComponent<typeof import("../components/volt/StepList.vue").default>
export const LazyVoltStepPanel: LazyComponent<typeof import("../components/volt/StepPanel.vue").default>
export const LazyVoltStepPanels: LazyComponent<typeof import("../components/volt/StepPanels.vue").default>
export const LazyVoltStepper: LazyComponent<typeof import("../components/volt/Stepper.vue").default>
export const LazyVoltTab: LazyComponent<typeof import("../components/volt/Tab.vue").default>
export const LazyVoltTabList: LazyComponent<typeof import("../components/volt/TabList.vue").default>
export const LazyVoltTabPanel: LazyComponent<typeof import("../components/volt/TabPanel.vue").default>
export const LazyVoltTabPanels: LazyComponent<typeof import("../components/volt/TabPanels.vue").default>
export const LazyVoltTabs: LazyComponent<typeof import("../components/volt/Tabs.vue").default>
export const LazyVoltTag: LazyComponent<typeof import("../components/volt/Tag.vue").default>
export const LazyVoltTextarea: LazyComponent<typeof import("../components/volt/Textarea.vue").default>
export const LazyVoltTimeline: LazyComponent<typeof import("../components/volt/Timeline.vue").default>
export const LazyVoltToast: LazyComponent<typeof import("../components/volt/Toast.vue").default>
export const LazyVoltToggleButton: LazyComponent<typeof import("../components/volt/ToggleButton.vue").default>
export const LazyVoltToggleSwitch: LazyComponent<typeof import("../components/volt/ToggleSwitch.vue").default>
export const LazyVoltToolbar: LazyComponent<typeof import("../components/volt/Toolbar.vue").default>
export const LazyVoltTree: LazyComponent<typeof import("../components/volt/Tree.vue").default>
export const LazyVoltUtils: LazyComponent<typeof import("../components/volt/utils").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default>
export const LazyAutoComplete: LazyComponent<typeof import("primevue/autocomplete").default>
export const LazyCalendar: LazyComponent<typeof import("primevue/calendar").default>
export const LazyCascadeSelect: LazyComponent<typeof import("primevue/cascadeselect").default>
export const LazyCheckbox: LazyComponent<typeof import("primevue/checkbox").default>
export const LazyCheckboxGroup: LazyComponent<typeof import("primevue/checkboxgroup").default>
export const LazyChips: LazyComponent<typeof import("primevue/chips").default>
export const LazyColorPicker: LazyComponent<typeof import("primevue/colorpicker").default>
export const LazyDatePicker: LazyComponent<typeof import("primevue/datepicker").default>
export const LazyDropdown: LazyComponent<typeof import("primevue/dropdown").default>
export const LazyFloatLabel: LazyComponent<typeof import("primevue/floatlabel").default>
export const LazyFluid: LazyComponent<typeof import("primevue/fluid").default>
export const LazyIconField: LazyComponent<typeof import("primevue/iconfield").default>
export const LazyIftaLabel: LazyComponent<typeof import("primevue/iftalabel").default>
export const LazyInputChips: LazyComponent<typeof import("primevue/inputchips").default>
export const LazyInputGroup: LazyComponent<typeof import("primevue/inputgroup").default>
export const LazyInputGroupAddon: LazyComponent<typeof import("primevue/inputgroupaddon").default>
export const LazyInputIcon: LazyComponent<typeof import("primevue/inputicon").default>
export const LazyInputMask: LazyComponent<typeof import("primevue/inputmask").default>
export const LazyInputNumber: LazyComponent<typeof import("primevue/inputnumber").default>
export const LazyInputOtp: LazyComponent<typeof import("primevue/inputotp").default>
export const LazyInputSwitch: LazyComponent<typeof import("primevue/inputswitch").default>
export const LazyInputText: LazyComponent<typeof import("primevue/inputtext").default>
export const LazyKnob: LazyComponent<typeof import("primevue/knob").default>
export const LazyListbox: LazyComponent<typeof import("primevue/listbox").default>
export const LazyMultiSelect: LazyComponent<typeof import("primevue/multiselect").default>
export const LazyPassword: LazyComponent<typeof import("primevue/password").default>
export const LazyRadioButton: LazyComponent<typeof import("primevue/radiobutton").default>
export const LazyRadioButtonGroup: LazyComponent<typeof import("primevue/radiobuttongroup").default>
export const LazyRating: LazyComponent<typeof import("primevue/rating").default>
export const LazySelect: LazyComponent<typeof import("primevue/select").default>
export const LazySelectButton: LazyComponent<typeof import("primevue/selectbutton").default>
export const LazySlider: LazyComponent<typeof import("primevue/slider").default>
export const LazyTextarea: LazyComponent<typeof import("primevue/textarea").default>
export const LazyToggleButton: LazyComponent<typeof import("primevue/togglebutton").default>
export const LazyToggleSwitch: LazyComponent<typeof import("primevue/toggleswitch").default>
export const LazyTreeSelect: LazyComponent<typeof import("primevue/treeselect").default>
export const LazyButton: LazyComponent<typeof import("primevue/button").default>
export const LazyButtonGroup: LazyComponent<typeof import("primevue/buttongroup").default>
export const LazySpeedDial: LazyComponent<typeof import("primevue/speeddial").default>
export const LazySplitButton: LazyComponent<typeof import("primevue/splitbutton").default>
export const LazyColumn: LazyComponent<typeof import("primevue/column").default>
export const LazyRow: LazyComponent<typeof import("primevue/row").default>
export const LazyColumnGroup: LazyComponent<typeof import("primevue/columngroup").default>
export const LazyDataTable: LazyComponent<typeof import("primevue/datatable").default>
export const LazyDataView: LazyComponent<typeof import("primevue/dataview").default>
export const LazyOrderList: LazyComponent<typeof import("primevue/orderlist").default>
export const LazyOrganizationChart: LazyComponent<typeof import("primevue/organizationchart").default>
export const LazyPaginator: LazyComponent<typeof import("primevue/paginator").default>
export const LazyPickList: LazyComponent<typeof import("primevue/picklist").default>
export const LazyTree: LazyComponent<typeof import("primevue/tree").default>
export const LazyTreeTable: LazyComponent<typeof import("primevue/treetable").default>
export const LazyTimeline: LazyComponent<typeof import("primevue/timeline").default>
export const LazyVirtualScroller: LazyComponent<typeof import("primevue/virtualscroller").default>
export const LazyAccordion: LazyComponent<typeof import("primevue/accordion").default>
export const LazyAccordionPanel: LazyComponent<typeof import("primevue/accordionpanel").default>
export const LazyAccordionHeader: LazyComponent<typeof import("primevue/accordionheader").default>
export const LazyAccordionContent: LazyComponent<typeof import("primevue/accordioncontent").default>
export const LazyAccordionTab: LazyComponent<typeof import("primevue/accordiontab").default>
export const LazyCard: LazyComponent<typeof import("primevue/card").default>
export const LazyDeferredContent: LazyComponent<typeof import("primevue/deferredcontent").default>
export const LazyDivider: LazyComponent<typeof import("primevue/divider").default>
export const LazyFieldset: LazyComponent<typeof import("primevue/fieldset").default>
export const LazyPanel: LazyComponent<typeof import("primevue/panel").default>
export const LazyScrollPanel: LazyComponent<typeof import("primevue/scrollpanel").default>
export const LazySplitter: LazyComponent<typeof import("primevue/splitter").default>
export const LazySplitterPanel: LazyComponent<typeof import("primevue/splitterpanel").default>
export const LazyStepper: LazyComponent<typeof import("primevue/stepper").default>
export const LazyStepList: LazyComponent<typeof import("primevue/steplist").default>
export const LazyStep: LazyComponent<typeof import("primevue/step").default>
export const LazyStepItem: LazyComponent<typeof import("primevue/stepitem").default>
export const LazyStepPanels: LazyComponent<typeof import("primevue/steppanels").default>
export const LazyStepPanel: LazyComponent<typeof import("primevue/steppanel").default>
export const LazyTabView: LazyComponent<typeof import("primevue/tabview").default>
export const LazyTabs: LazyComponent<typeof import("primevue/tabs").default>
export const LazyTabList: LazyComponent<typeof import("primevue/tablist").default>
export const LazyTab: LazyComponent<typeof import("primevue/tab").default>
export const LazyTabPanels: LazyComponent<typeof import("primevue/tabpanels").default>
export const LazyTabPanel: LazyComponent<typeof import("primevue/tabpanel").default>
export const LazyToolbar: LazyComponent<typeof import("primevue/toolbar").default>
export const LazyConfirmDialog: LazyComponent<typeof import("primevue/confirmdialog").default>
export const LazyConfirmPopup: LazyComponent<typeof import("primevue/confirmpopup").default>
export const LazyDialog: LazyComponent<typeof import("primevue/dialog").default>
export const LazyDrawer: LazyComponent<typeof import("primevue/drawer").default>
export const LazyDynamicDialog: LazyComponent<typeof import("primevue/dynamicdialog").default>
export const LazyOverlayPanel: LazyComponent<typeof import("primevue/overlaypanel").default>
export const LazyPopover: LazyComponent<typeof import("primevue/popover").default>
export const LazySidebar: LazyComponent<typeof import("primevue/sidebar").default>
export const LazyFileUpload: LazyComponent<typeof import("primevue/fileupload").default>
export const LazyBreadcrumb: LazyComponent<typeof import("primevue/breadcrumb").default>
export const LazyContextMenu: LazyComponent<typeof import("primevue/contextmenu").default>
export const LazyDock: LazyComponent<typeof import("primevue/dock").default>
export const LazyMenu: LazyComponent<typeof import("primevue/menu").default>
export const LazyMenubar: LazyComponent<typeof import("primevue/menubar").default>
export const LazyMegaMenu: LazyComponent<typeof import("primevue/megamenu").default>
export const LazyPanelMenu: LazyComponent<typeof import("primevue/panelmenu").default>
export const LazySteps: LazyComponent<typeof import("primevue/steps").default>
export const LazyTabMenu: LazyComponent<typeof import("primevue/tabmenu").default>
export const LazyTieredMenu: LazyComponent<typeof import("primevue/tieredmenu").default>
export const LazyMessage: LazyComponent<typeof import("primevue/message").default>
export const LazyInlineMessage: LazyComponent<typeof import("primevue/inlinemessage").default>
export const LazyToast: LazyComponent<typeof import("primevue/toast").default>
export const LazyCarousel: LazyComponent<typeof import("primevue/carousel").default>
export const LazyGalleria: LazyComponent<typeof import("primevue/galleria").default>
export const LazyImage: LazyComponent<typeof import("primevue/image").default>
export const LazyImageCompare: LazyComponent<typeof import("primevue/imagecompare").default>
export const LazyAvatar: LazyComponent<typeof import("primevue/avatar").default>
export const LazyAvatarGroup: LazyComponent<typeof import("primevue/avatargroup").default>
export const LazyBadge: LazyComponent<typeof import("primevue/badge").default>
export const LazyBlockUI: LazyComponent<typeof import("primevue/blockui").default>
export const LazyChip: LazyComponent<typeof import("primevue/chip").default>
export const LazyInplace: LazyComponent<typeof import("primevue/inplace").default>
export const LazyMeterGroup: LazyComponent<typeof import("primevue/metergroup").default>
export const LazyOverlayBadge: LazyComponent<typeof import("primevue/overlaybadge").default>
export const LazyScrollTop: LazyComponent<typeof import("primevue/scrolltop").default>
export const LazySkeleton: LazyComponent<typeof import("primevue/skeleton").default>
export const LazyProgressBar: LazyComponent<typeof import("primevue/progressbar").default>
export const LazyProgressSpinner: LazyComponent<typeof import("primevue/progressspinner").default>
export const LazyTag: LazyComponent<typeof import("primevue/tag").default>
export const LazyTerminal: LazyComponent<typeof import("primevue/terminal").default>
export const LazyForm: LazyComponent<typeof import("@primevue/forms/form").default>
export const LazyFormField: LazyComponent<typeof import("@primevue/forms/formfield").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
